### ISSUE TITLE
Renew plugin from scratch

### ISSUE THREAD

**Issue by kamalkhan** [kamalkhan/kk-star-ratings#18]
I am currently working on a framework and will be building the plugin from scratch so until then I will not be fixing the current issues as they will be deprecated.

**Comment by tosunkaya** [comment]
Very good.

**Comment by melleman** [comment]
Nice. Did you have a timelane when the new version will go online?

**Comment by kamalkhan** [comment]
I will be updating the master branch of this repository very soon so everyone will be able to jump right in.

**Comment by leecollings** [comment]
Hey @kamalkhan I've just seen this message, and was about to try and dive into fixing a notice that's appearing when using PHP 7.1.1, but not sure if it's worth it after reading this post.

`Notice: A non well formed numeric value encountered in \wp-content\plugins\kk-star-ratings\index.php on line 606`

Line 606: `$per = ($raw>0?ceil((($raw/$cast)/5)*100):0).'%';`

Just in case this is useful for you at all? Appears in the 'Order' column when viewing Pages in WP Admin.

**Comment by Tobias-Conrad** [comment]
@kamalkhan Hi, i want to thank you for the nice plugin. Can you finish your framework and release a new version with bugs fixed. You can advertise your development service inside your plugin to raise money for your update efforts.

**Comment by kamalkhan** [comment]
@Tobias-Conrad Thank you for your concern. I have been shifting from one product to another from time to time as I am not able to allocate a consistent required time to continue open source development. A side project had come up during the development of the framework so I had to switch away. I will try my best to come back at this asap, no guarantees I am afraid.

**Comment by Tobias-Conrad** [comment]
May you enter the pareto 80/20 system do 20% for 80% outcome.

**Comment by tanazmusic** [comment]
it,s good
thanks
[دانلود آهنگ](http://tanazmusic.ir/)
[طناز موزیک](http://tanazmusic.ir)
[download new music](http://tanazmusic.ir/)

**Comment by Tobias-Conrad** [comment]
and you did update the plugin thanks a lot for that

**Comment by ecodar** [comment]
I found a temporary solution to move KK Star rating Javascript to the footer. Because of I build WP theme from scratch, I registered jQuery to footer and use CDN service. Here is what I do so far:

Add this line code to function.php
wp_deregister_script( 'jquery');	
wp_register_script( 'jquery', 'https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js', null, null, true );

Modify kk-star-ratings ver 2.6.1 @ kk-star-ratings\index.php
Before: 
$this->enqueue_js('js', self::file_uri('js.min.js'), $this->ver, array('jquery'), $Params, false, true);
After:  
$this->enqueue_js('js', self::file_uri('js.min.js'), $this->ver, array('jquery'), $Params, true, true);

**Comment by web-corp-eu** [comment]
Don't show stars in google
