### ISSUE TITLE
render javascript by wp_head instead

### ISSUE THREAD

**Issue by saekoew** [kamalkhan/kk-star-ratings#48]
function enqueue_js in bhittani-framework/plugin.php
There is code to render javascript. Sometimes it writes javascript before html tag.

**Comment by kamalkhan** [comment]
I am currently working on something else and in the process of recreating the plugin. So for now i would recommend you to modify the code however you see fit. I am also open to pull requests.

**Comment by stodorovic** [comment]
This code could break sitemaps/feeds in some cases. I just created #48 which uses function wp_add_inline_script if it exists ( WP>=4.5 ). So, it seems as correct solution because a lot of users have installed newer WP. Older WP version will use old code.
@saekoew Could you test this PR? I tried some basic test and JS code is on proper place.
